[project]
name = "netol-classes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "kaggle>=1.7.4.5",
    "matplotlib>=3.10.3",
    "nltk>=3.9.1",
    "pandas>=2.3.1",
    "pymorphy2==0.9.1",
    "pymorphy3>=2.0.6",
    "rusenttokenize>=0.0.5",
    "scikit-learn>=1.7.1",
]
